/* src/config.h.  Generated by configure.  */
/* src/config.h.in.  Generated from configure.ac by autoheader.  */

/* Define to 1 if you have the `bzero' function. */
#define HAVE_BZERO 1

/* Define to 1 if you have the `fstat' function. */
#define HAVE_FSTAT 1

/* Define to 1 if you have the `fsync' function. */
#define HAVE_FSYNC 1

/* Define to 1 if you have the `getpt' function. */
#define HAVE_GETPT 1

/* Define to 1 if you have the `getrlimit' function. */
#define HAVE_GETRLIMIT 1

/* Define to 1 if you have the `memset' function. */
#define HAVE_MEMSET 1

/* Define to 1 if you have the `snprintf' function. */
#define HAVE_SNPRINTF 1

/* Define to 1 if you have the `strlcat' function. */
/* #undef HAVE_STRLCAT */

/* Define to 1 if you have the `strlcpy' function. */
/* #undef HAVE_STRLCPY */

/* Define to 1 if you have the `usleep' function. */
#define HAVE_USLEEP 1

/* Define to 1 if you have the `utime' function. */
#define HAVE_UTIME 1

/* Define to 1 if you have the `utimes' function. */
#define HAVE_UTIMES 1

/* Name of package */
#define PACKAGE "ce"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "Robert Styma <styma@swlink.net>"

/* Define to the full name of this package. */
#define PACKAGE_NAME "ARPUS/Ce"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "ARPUS/Ce 2.6.1-d"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "ce"

/* Define to the version of this package. */
#define PACKAGE_VERSION "2.6.1-d"

/* Whether to enable System V compatibility */
/* #undef SYSV */

/* Version number of package */
#define VERSION "2.6.1"
